if not ((mods["tenebris"] or mods["tenebris-prime"]) and mods["dredgeworks"]) then
	return
end

local logl = require("lib.log")
local mlib = require("lib.manipulation")

logl.info("Removing floating bioluminescents...")

local function is_floating_bioluminescent(prototype)
	local match = string.sub(prototype.name, 1, string.len("floating-bioluminescent-"))
	return match == "floating-bioluminescent-" or match == "bioluminescent-floating-"
end

mlib.add_defer_operation("remove-floating-logistics", function(prototype)
	mlib.remove_item(prototype.name, {
		item_type = { "item", "inserter", "transport-belt" },
		quiet_miss = true, -- overly broad search on purpose :)
		remove_recycling = true,
		remove_from_technologies = { "floating-logistics-technology", "bioinfusor" },
	})
end)

-- deal with autogenerated recipes (looking at you, paracelsin 1.7.0)
mlib.add_defer_operation("remove-recipe", function(prototype)
	mlib.remove({ "recipe", prototype.name })
end)

mlib.defer("item", is_floating_bioluminescent, "remove-floating-logistics")
mlib.defer("recipe", is_floating_bioluminescent, "remove-recipe")
